{
 "title": "latest",
 "description": "This is a modern 'Nodes View' dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster\"}, node)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "Pod", "label": "Pod", "query": { "query": "label_values(pod)" } },
   { "name": "pod_phase", "label": "pod_phase", "query": { "query": "label_values(phase)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Cluster CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{} - node_memory_MemAvailable_bytes{}) / sum(node_memory_MemTotal_bytes{})"
    }
   ]
  },
  {
   "title": "Cluster total CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(machine_cpu_cores{})" }
   ]
  },
  {
   "title": "Total Nodes ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_info)" }
   ]
  },
  {
   "title": "Cluster total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)/ (1000^3)"
    }
   ]
  },
  { "title": "Node Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node CPU  Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", node=~\"$node\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "Node RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$node\"} - node_memory_MemAvailable_bytes{node=~\"$node\"}) / sum(node_memory_MemTotal_bytes{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Node total CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node total Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$node\"})/ (1000^3)"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum((node_filesystem_size_bytes{node=~\"$node\",mountpoint=\"/etc/hostname\"} - node_filesystem_avail_bytes{node=~\"$node\",mountpoint=\"/etc/hostname\"})) / sum(node_filesystem_size_bytes{node=~\"$node\",mountpoint=\"/etc/hostname\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods on node",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "List of pods on node ($node)",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 18 },
   "targets": [
    {
     "expr": "kube_pod_info{node=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Pod Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  },
  {
   "title": "Pod Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"$pod_phase\"}"
    }
   ]
  }
 ]
}